# Generated by Django 5.1.6 on 2025-08-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='init_data',
        ),
        migrations.RemoveField(
            model_name='user',
            name='web_app_query_id',
        ),
    ]
