# Generated by Django 5.1.6 on 2025-08-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_init_data_remove_user_web_app_query_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='user',
            name='bmi',
            field=models.FloatField(blank=True, null=True, verbose_name='ИМТ'),
        ),
    ]
