# Generated by Django 5.1.6 on 2025-08-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_init_data_user_is_bot_user_web_app_query_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='language',
            new_name='language_code',
        ),
    ]
