# Generated by Django 5.1.6 on 2025-08-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_age_user_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_type',
            field=models.CharField(blank=True, choices=[('MONTH', 'Месячная'), ('YEAR', 'На год')], default=None, max_length=30, null=True, verbose_name='Тип подписки'),
        ),
    ]
