# Generated by Django 5.1.6 on 2025-08-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language_code',
            field=models.CharField(blank=True, default='ru', max_length=10, null=True),
        ),
    ]
