# Generated by Django 5.1.6 on 2025-08-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Другое')], max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_bot',
            field=models.BooleanField(default=False, verbose_name='Бот'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Премиум подписка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language_code',
            field=models.CharField(blank=True, default='ru', max_length=10, null=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='premium_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание подписки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец пробного периода'),
        ),
        migrations.AlterField(
            model_name='user',
            name='trial_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Не начат'), ('IN_PROGRESS', 'В процессе'), ('ENDED', 'Окончен')], default='NOT_STARTED', max_length=12, verbose_name='Пробный период'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Вес'),
        ),
    ]
