# Generated by Django 5.1.6 on 2025-08-19 19:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1900, 1, 1), message='Дата рождения не может быть раньше 1900 года.')], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50, message='Рост не может быть меньше 50 см.'), django.core.validators.MaxValueValidator(250, message='Рост не может быть больше 250 см.')], verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(20, message='Вес не может быть меньше 20 кг.'), django.core.validators.MaxValueValidator(300, message='Вес не может быть больше 300 кг.')], verbose_name='Вес'),
        ),
    ]
