# Generated by Django 5.1.6 on 2025-08-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_birth_date_alter_user_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Откуда узнали о приложении'),
        ),
    ]
