# Generated by Django 5.1.6 on 2025-08-28 15:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='callories',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Калории'),
        ),
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='training',
            name='intensity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True, verbose_name='Интенсивность'),
        ),
        migrations.AlterField(
            model_name='training',
            name='type',
            field=models.CharField(choices=[('run', 'Run'), ('gym', 'Gym'), ('manual', 'Manual')], max_length=10, verbose_name='Тип тренировки'),
        ),
        migrations.AlterField(
            model_name='training',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
